wso2-extensions/identity-oauth-uma

components/org.wso2.carbon.identity.oauth.uma.permission.service/src/main/java/org/wso2/carbon/identity/oauth/uma/permission/service/dao/PermissionTicketDAO.java

Check resource scope existence.

---

components/org.wso2.carbon.identity.oauth.uma.permission.endpoint/src/main/java/org/wso2/carbon/identity/oauth/uma/permission/endpoint/PermissionApiServiceImpl.java
components/org.wso2.carbon.identity.oauth.uma.permission.endpoint/src/main/resources/permission_endpoint.yaml
components/org.wso2.carbon.identity.oauth.uma.permission.endpoint/src/test/java/org/wso2/carbon/identity/oauth/uma/permission/endpoint/PermissionApiServiceImplTest.java
components/org.wso2.carbon.identity.oauth.uma.permission.service/src/main/java/org/wso2/carbon/identity/oauth/uma/permission/service/PermissionService.java
components/org.wso2.carbon.identity.oauth.uma.permission.service/src/main/java/org/wso2/carbon/identity/oauth/uma/permission/service/UMAConstants.java
components/org.wso2.carbon.identity.oauth.uma.permission.service/src/main/java/org/wso2/carbon/identity/oauth/uma/permission/service/dao/PermissionTicketDAO.java
components/org.wso2.carbon.identity.oauth.uma.permission.service/src/main/java/org/wso2/carbon/identity/oauth/uma/permission/service/exception/UMAClientException.java
components/org.wso2.carbon.identity.oauth.uma.permission.service/src/main/java/org/wso2/carbon/identity/oauth/uma/permission/service/exception/UMAException.java
components/org.wso2.carbon.identity.oauth.uma.permission.service/src/main/java/org/wso2/carbon/identity/oauth/uma/permission/service/exception/UMAServerException.java
components/org.wso2.carbon.identity.oauth.uma.permission.service/src/main/java/org/wso2/carbon/identity/oauth/uma/permission/service/impl/PermissionServiceImpl.java
components/org.wso2.carbon.identity.oauth.uma.permission.service/src/test/java/org/wso2/carbon/identity/oauth/uma/permission/service/dao/PermissionTicketDAOTest.java
components/org.wso2.carbon.identity.oauth.uma.permission.service/src/test/java/org/wso2/carbon/identity/oauth/uma/permission/service/impl/PermissionServiceImplTest.java
pom.xml

Change HandleErrorResponse.

---

pom.xml

Part of fix for wso2/product-is#3140
**Needs to be merged after merging** https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/879

Update oauth version to 6.0.0

---

components/org.wso2.carbon.identity.oauth.uma.common/pom.xml

Change uma common version.

---

components/org.wso2.carbon.identity.oauth.uma.xacml.extention/pom.xml
pom.xml

Fix build fail by changing pom version.

---

components/org.wso2.carbon.identity.oauth.uma.xacml.extention/pom.xml
components/org.wso2.carbon.identity.oauth.uma.xacml.extention/src/main/java/org/wso2/carbon/identity/oauth/uma/xacml/service/handler/XACMLUMAHandler.java
components/org.wso2.carbon.identity.oauth.uma.xacml.extention/src/main/java/org/wso2/carbon/identity/oauth/uma/xacml/service/internal/AppUMAServiceComponents.java

Remove policy Evaluator.

---

components/org.wso2.carbon.identity.oauth.uma.common/src/main/java/org/wso2/carbon/identity/oauth/uma/common/UMAConstants.java
components/org.wso2.carbon.identity.oauth.uma.permission.service/src/main/java/org/wso2/carbon/identity/oauth/uma/permission/service/dao/PermissionTicketDAO.java

Extract resource ID's and scopes from permission Ticket.

---

components/org.wso2.carbon.identity.oauth.uma.permission.service/src/main/java/org/wso2/carbon/identity/oauth/uma/permission/service/dao/PermissionTicketDAO.java

> fixes an issue with H2DB when getting the permission ticket expiry time.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content …

Passed Calendar object when getting timestamp from result set

---

components/org.wso2.carbon.identity.oauth.uma.resource.endpoint/src/gen/java/org/wso2/carbon/identity/oauth/uma/resource/endpoint/ResourceRegistrationApi.java
components/org.wso2.carbon.identity.oauth.uma.resource.endpoint/src/gen/java/org/wso2/carbon/identity/oauth/uma/resource/endpoint/dto/CreateResourceDTO.java
components/org.wso2.carbon.identity.oauth.uma.resource.endpoint/src/gen/java/org/wso2/carbon/identity/oauth/uma/resource/endpoint/dto/ListReadResourceDTO.java
components/org.wso2.carbon.identity.oauth.uma.resource.endpoint/src/gen/java/org/wso2/carbon/identity/oauth/uma/resource/endpoint/dto/ReadResourceDTO.java
components/org.wso2.carbon.identity.oauth.uma.resource.endpoint/src/gen/java/org/wso2/carbon/identity/oauth/uma/resource/endpoint/dto/ResourceDetailsDTO.java
components/org.wso2.carbon.identity.oauth.uma.resource.endpoint/src/gen/java/org/wso2/carbon/identity/oauth/uma/resource/endpoint/dto/UpdateResourceDTO.java
components/org.wso2.carbon.identity.oauth.uma.resource.endpoint/src/main/java/org/wso2/carbon/identity/oauth/uma/resource/endpoint/util/ResourceUtils.java
components/org.wso2.carbon.identity.oauth.uma.resource.endpoint/src/main/resources/api.identity.oauth.uma.resource.endpoint.yaml
components/org.wso2.carbon.identity.oauth.uma.resource.endpoint/src/test/java/org/wso2/carbon/identity/oauth/uma/resource/endpoint/util/ResourceUtilsTest.java

Change parameter names for resource registration endpoint.

---

components/org.wso2.carbon.identity.oauth.uma.permission.endpoint/pom.xml
components/org.wso2.carbon.identity.oauth.uma.permission.endpoint/src/main/webapp/META-INF/webapp-classloading.xml
components/org.wso2.carbon.identity.oauth.uma.permission.endpoint/src/main/webapp/WEB-INF/beans.xml
components/org.wso2.carbon.identity.oauth.uma.resource.endpoint/pom.xml
components/org.wso2.carbon.identity.oauth.uma.resource.endpoint/src/main/webapp/META-INF/webapp-classloading.xml
components/org.wso2.carbon.identity.oauth.uma.resource.endpoint/src/main/webapp/WEB-INF/beans.xml

Merge this PR after merging https://github.com/wso2/carbon-deployment/pull/300

Upgrade CXF version 

---

components/org.wso2.carbon.identity.oauth.uma.grant/pom.xml

This PR updates the checkstyle config file location.

Update checkstyle config file location

---

components/org.wso2.carbon.identity.oauth.uma.permission.endpoint/src/main/webapp/WEB-INF/web.xml
components/org.wso2.carbon.identity.oauth.uma.resource.endpoint/src/main/webapp/WEB-INF/web.xml

Add java 11 support

---

components/org.wso2.carbon.identity.oauth.uma.permission.endpoint/src/main/webapp/WEB-INF/web.xml
components/org.wso2.carbon.identity.oauth.uma.resource.endpoint/src/main/webapp/WEB-INF/web.xml
pom.xml

 Skip annotation scanner for web apps and version update

---

components/org.wso2.carbon.identity.oauth.uma.grant/pom.xml
components/org.wso2.carbon.identity.oauth.uma.resource.service/pom.xml
components/org.wso2.carbon.identity.oauth.uma.xacml.extension/pom.xml
components/org.wso2.carbon.identity.oauth.uma.xacml.extension/src/main/java/org/wso2/carbon/identity/oauth/uma/xacml/service/internal/AppUMAServiceComponents.java
pom.xml

> Update version for kernel m3

Update version for kernel m3

---

components/org.wso2.carbon.identity.oauth.uma.grant/pom.xml
components/org.wso2.carbon.identity.oauth.uma.permission.service/pom.xml
components/org.wso2.carbon.identity.oauth.uma.resource.service/pom.xml
components/org.wso2.carbon.identity.oauth.uma.xacml.extension/pom.xml

Remove scr plugin

---

pom.xml

Fix export version

---

components/org.wso2.carbon.identity.oauth.uma.common/src/main/java/org/wso2/carbon/identity/oauth/uma/common/HandleErrorResponseConstants.java

Fixing comments in: https://github.com/wso2-extensions/identity-oauth-uma/pull/1

Addressing comments.

---

components/org.wso2.carbon.identity.oauth.uma.grant/pom.xml
components/org.wso2.carbon.identity.oauth.uma.grant/src/main/java/org/wso2/carbon/identity/oauth/uma/grant/UMA2GrantHandler.java

Fixes https://github.com/wso2/product-is/issues/7264
Start a tenant flow before validating the ticket sent in the request.

Validate XACML policies in tenant flow

---

components/org.wso2.carbon.identity.oauth.uma.grant/src/main/java/org/wso2/carbon/identity/oauth/uma/grant/UMA2GrantHandler.java

Resolves https://github.com/wso2/product-is/issues/7634

Set tenant domain in AuthenticatedUser object

---

components/org.wso2.carbon.identity.oauth.uma.common/pom.xml
components/org.wso2.carbon.identity.oauth.uma.grant/pom.xml
components/org.wso2.carbon.identity.oauth.uma.permission.endpoint/pom.xml
components/org.wso2.carbon.identity.oauth.uma.permission.service/pom.xml
components/org.wso2.carbon.identity.oauth.uma.resource.endpoint/pom.xml
components/org.wso2.carbon.identity.oauth.uma.resource.service/pom.xml
components/org.wso2.carbon.identity.oauth.uma.xacml.extension/pom.xml
features/org.wso2.carbon.identity.oauth.uma.server.feature/pom.xml
pom.xml

Upgrade Carbon Kernel version

---

components/org.wso2.carbon.identity.oauth.uma.grant/src/main/java/org/wso2/carbon/identity/oauth/uma/grant/UMA2GrantHandler.java
components/org.wso2.carbon.identity.oauth.uma.resource.endpoint/src/main/java/org/wso2/carbon/identity/oauth/uma/resource/endpoint/impl/ResourceRegistrationApiServiceImpl.java
pom.xml

Fixes https://github.com/wso2/product-is/issues/8625

Tenant qualify UMA endpoints

---

components/org.wso2.carbon.identity.oauth.uma.grant/pom.xml
components/org.wso2.carbon.identity.oauth.uma.resource.service/pom.xml
components/org.wso2.carbon.identity.oauth.uma.xacml.extension/pom.xml
pom.xml

Resolves: https://github.com/wso2/product-is/issues/9360

Remove mysql-connector-java dependency.

---

components/org.wso2.carbon.identity.oauth.uma.permission.endpoint/pom.xml
components/org.wso2.carbon.identity.oauth.uma.resource.endpoint/pom.xml
pom.xml

Issue: https://github.com/wso2/product-is/issues/9542
Ran IS integration tests locally.

Update jackson-mapper-asl to jackson-databind

---

components/org.wso2.carbon.identity.oauth.uma.permission.service/src/main/java/org/wso2/carbon/identity/oauth/uma/permission/service/dao/PermissionTicketDAO.java
pom.xml

Part of the fix for wso2/product-is#9010

Add support for maria db

---

components/org.wso2.carbon.identity.oauth.uma.permission.service/src/main/java/org/wso2/carbon/identity/oauth/uma/permission/service/impl/PermissionServiceImpl.java

> Fixing https://github.com/wso2/product-is/issues/11351

Add support to handle JWTs in UMAIntrospectionDataProvider

---

components/org.wso2.carbon.identity.oauth.uma.permission.service/src/main/java/org/wso2/carbon/identity/oauth/uma/permission/service/impl/PermissionServiceImpl.java
pom.xml

Add Update commits to 1.2.x

---

components/org.wso2.carbon.identity.oauth.uma.common/pom.xml
components/org.wso2.carbon.identity.oauth.uma.grant/pom.xml
components/org.wso2.carbon.identity.oauth.uma.permission.endpoint/pom.xml
components/org.wso2.carbon.identity.oauth.uma.permission.service/pom.xml
components/org.wso2.carbon.identity.oauth.uma.resource.endpoint/pom.xml
components/org.wso2.carbon.identity.oauth.uma.resource.service/pom.xml
components/org.wso2.carbon.identity.oauth.uma.xacml.extension/pom.xml
features/org.wso2.carbon.identity.oauth.uma.server.feature/pom.xml
pom.xml

Update snapshot version

---

components/org.wso2.carbon.identity.api.server.oauth.uma.permission/pom.xml
components/org.wso2.carbon.identity.api.server.oauth.uma.resource/pom.xml
components/org.wso2.carbon.identity.oauth.uma.permission.endpoint/pom.xml
components/org.wso2.carbon.identity.oauth.uma.resource.endpoint/pom.xml
pom.xml

Upgrade jackson dependencies to `v2.13.2` and jackson databind to `v2.13.2.1`

Upgrade jackson dependencies to v2.13.2 and jackson databind to v2.13.2.1

---

docs/config.md
docs/tryout.md

$subject
- https://github.com/wso2/product-is/issues/15519

Update UMA introspection configuration

---

components/org.wso2.carbon.identity.oauth.uma.grant/pom.xml
pom.xml

Fix startup issues

---

.connector-store/meta.json

Add support for IS-7.1.0

---

.github/workflows/pr-builder.yml
components/org.wso2.carbon.identity.api.server.oauth.uma.permission/pom.xml
components/org.wso2.carbon.identity.api.server.oauth.uma.resource/pom.xml
components/org.wso2.carbon.identity.oauth.uma.common/pom.xml
components/org.wso2.carbon.identity.oauth.uma.grant/pom.xml
components/org.wso2.carbon.identity.oauth.uma.permission.endpoint/pom.xml
components/org.wso2.carbon.identity.oauth.uma.permission.service/pom.xml
components/org.wso2.carbon.identity.oauth.uma.resource.endpoint/pom.xml
components/org.wso2.carbon.identity.oauth.uma.resource.service/pom.xml
components/org.wso2.carbon.identity.oauth.uma.xacml.extension/pom.xml
features/org.wso2.carbon.identity.oauth.uma.server.feature/pom.xml
pom.xml

Release a major version with Spring Removal
